### ISSUE TITLE
execute_kw seems to break SearchAndRead

### ISSUE THREAD

**Issue by Sunradon** [ieski/OdooXmlRpc#10]
I just updated to the latest version of this project and had an immediate problem just trying to do a simple SearchAndRead operation. Here is a minimal code snippet that demonstrates the problem:

            RpcContext rpcContext = new RpcContext(_odooConn, model);
            rpcContext
                .RpcFilter
                .Equal("id", 1);
            IEnumerable<RpcRecord> data = rpcContext.Execute(true, 0, limit: 1);

If I use pcContext.Execute(false, 0, limit: 1); instead it succeeds but I get no data returned. When I set the read argument to true, Odoo returns me this: TypeError: execute_kw() takes from 5 to 6 positional arguments but 9 were given.

My workaround is to edit IObjRpc.cs line 16 to use "execute" instead of "execute_kw". I see that execute_kw is pretty awesome for calling methods but it just doesn't work yet for search_read. I do see that you changed the sample code to not use this feature, so perhaps you're already aware?

Also, I made a very slight improvement in the RpcRecord.cs "ToString" function to help expand many2one fields. Would you be interested in additional contributors to your project?
Best Regards,
Garrett Clark

**Comment by ieski** [comment]
I fixed the problem, Would you like to contributor?
Thanks.
