### ISSUE TITLE
account.invoice.line cannot be returned

### ISSUE THREAD

**Issue by dsonnet** [ieski/OdooXmlRpc#2]
Hi

            var odooConn = new RpcConnection(rpcConnnectionSettings);
            var rpcContext = new RpcContext(odooConn, "account.invoice.line");
            var data = rpcContext.Execute(true, limit:5);

Is failing with "Fault Response Contains a String value where an Integer was Expected"

I see the _objectRpc.NonStandard = XmlRpcNonStandard.AllowStringFaultCode;

but this doesn't seem to work

**Comment by ieski** [comment]
Hi.

Check the server address and port.

Sample:

`{
  "OdooConnection": {
    "ServerUrl": "https://demo.odootr.com",
    "DbName": "Odoo-SMB-ERP",
    "DbUser": "admin",
    "DbPassword": "admin",
    "ImmediateLogin": true,
    "ServerCertificateValidation": true
  }
}`
