### ISSUE TITLE
RpcRecord.SetFieldValue fails to set value to false when type is boolen

### ISSUE THREAD

**Issue by micahsdad1402** [ieski/OdooXmlRpc#21]
When setting a field type boolean to false, the SetFieldValue sets the field to null, which then crashes with null object when saving.

**To Reproduce**
`RpcRecord Opportunity = odooOpportunities.GetOpportunity(dealOpportunity.Id);
Opportunity.SetFieldValue("active", (Boolean)false);
Opportunity.Save();`
**Expected behavior**
The value should be set to false.

The solution is add test fpr boolean as well as bool. TBH I've no idea why the code even does this.

`       public object Value
        {
            get
            {
                if (Type != "bool" && Type != "boolean" && _value is bool && ((bool)_value) == false)
                {
                    return DefaultValue;
                }
                return _value;
            }
            set
            {
                _value = value;
            }
        }`

![image](https://github.com/ieski/OdooXmlRpc/assets/15971421/2b834729-0821-40e6-b799-627ef84f5f59)
s
I tried casting to bool rather than Boolean ie (bool)false, and get the same result with the type being "boolean"

**Comment by ieski** [comment]
Hi,

I made the arrangement as you mentioned. 

Thank you

**Comment by ieski** [comment]
Hi,

I made the arrangement as you mentioned.

Thank you
